name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  prep-images:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.targets-with-image-label.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          repository-cache: true
      - id: targets-with-image-label
        run: |
          PACKAGES=$(bazel query 'kind(oci_image, //...)' --output package | jq -Rcs 'split("\n") | map(select(length > 0))')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    needs:
      - prep-images
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.prep-images.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          repository-cache: true
      - run: bazel build //${{ matrix.package }}:image
